feat: adding certificate delivery subscriptions
topos-protocol/topos pull request #328
Opened 2023-10-05 13:30 UTC by Freyskeyd

# Description

Wire the `broadcast` delivered certificates notification into the new `GraphQL` subscriptions.

An example query: 
![Screenshot 2023-10-05 at 15 26 17](https://github.com/topos-protocol/topos/assets/1394604/8730ae3c-0e4e-4c90-9251-5eb2a32e7788)

A `Websocket` is used to expose and push messages to the frontend.

## PR Checklist:

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added or updated tests that comprehensively prove my change is effective or that my feature works

2023-10-05 17:52 UTC, gruberb requested changes
👍

2023-10-09 14:12 UTC, dvdplm approved these changes
Left some comments and questions but overall this looks like it's ready to go.

2023-10-09 16:15 UTC, Freyskeyd commented on crates/topos-tce-api/src/graphql/filter.rs
> +pub(crate) enum FilterIs {
The point is to represent the type of filter used, having just a `bool` wasn't clear.
If you have any suggestion feel free

2023-10-09 16:19 UTC, Freyskeyd commented on crates/topos-tce-api/src/runtime/mod.rs
> +                // Each stream will convert the UCI certificate into a GraphQL one and send it to the transient stream.
You mean where is the conversion defined between UCI struct and GraphQL struct? If yes, it's [here](https://github.com/topos-protocol/topos/blob/main/crates/topos-api/src/graphql/certificate.rs#L26)
If you're talking about where we execute the conversion it's [here](https://github.com/topos-protocol/topos/blob/main/crates/topos-tce-api/src/graphql/query.rs#L136)

2023-10-09 16:41 UTC, Freyskeyd commented on crates/topos-tce-api/src/graphql/query.rs
> +    /// This endpoint is used to received delivered certificates.
mmh technically you're watching certificates, the `stream` is the transport. I find it less clear to talk about `stream of delivered certificates` as the output of this API call is that we receive `certificate`

2023-10-11 13:36 UTC, atanmarko approved these changes

2023-10-11 13:58 UTC, dvdplm commented on crates/topos-tce-api/src/runtime/mod.rs
> +                // Each stream will convert the UCI certificate into a GraphQL one and send it to the transient stream.
🙏

2023-10-11 14:02 UTC, dvdplm commented on crates/topos-tce-api/src/graphql/filter.rs
> +pub(crate) enum FilterIs {
How about just `Origin`? Or `OriginFilter`.

2023-10-11 14:03 UTC, dvdplm commented
@gruberb Can you re-review please and let us know if you still have concerns?

2023-10-11 17:33 UTC, gruberb approved these changes
👍

2023-10-18 06:39 UTC, merged