feat: add dedicated websocket cli parameter
topos-protocol/topos pull request #337
Opened 2023-10-11 14:54 UTC by atanmarko

# Description

Add sequencer command line argument `--subnet-websocket-endpoint` to explicitly provided subnet jsonrpc websocket endpoint. Usable when subnet endpoint could not be derived from ` http/https` endpoint in a standard way (what is done by default)

Fixes TP-749

## PR Checklist:

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added or updated tests that comprehensively prove my change is effective or that my feature works

2023-10-12 21:37 UTC, hadjiszs reviewed
I think the initial idea is more to make it straight and not flexible, simply `subnet_http_jsonrpc_endpoint` and `subnet_ws_jsonrpc_endpoint` given explicitly, without any attempt to infer anything

Here the current patch is nice because pretty backward compatible with what we have now, but the concern is that's the type of weird logic that are not nice when they adds up I think

2023-10-12 21:37 UTC, hadjiszs commented on crates/topos/src/components/sequencer/commands/run.rs
> +    pub subnet_websocket_endpoint: Option<String>,
I'd mention about that on the description of `subnet_jsonrpc_endpoint` too

(also `///` for the rustdoc)

2023-10-13 08:39 UTC, dvdplm requested changes
I think we should stop inferring things automatically, like @hadjiszs suggests.

Also, wrt naming: JSON-RPC is the *protocol* and http/ws are the available *transports*. With that in mind I think `subnet_websocket_endpoint` is a poor name. I suggest we rename the options to `subnet_jsonrpc_http` and `subnet_jsonrpc_ws` and make both required (no `Option<String>`).

I am a bit concerned about our naming of env vars; I think they should be consistently prefixed with `TOPOS_`, but that's something for a different PR. :)

2023-10-13 08:43 UTC, atanmarko commented
> I think we should stop inferring things automatically, like @hadjiszs suggests.
> 
> Also, wrt naming: JSON-RPC is the _protocol_ and http/ws are the available _transports_. With that in mind I think `subnet_websocket_endpoint` is a poor name. I suggest we rename the options to `subnet_jsonrpc_http` and `subnet_jsonrpc_ws` and make both required (no `Option<String>`).
> 
> I am a bit concerned about our naming of env vars; I think they should be consistently prefixed with `TOPOS_`, but that's something for a different PR. :)

Right I am aware of that. I didn't want to break things with the tools team setup (to rename the subnet_jsonrpc_endpoint) and add topos to the env variable. Lets break everything then.

2023-10-13 09:54 UTC, atanmarko commented
@dvdplm @hadjiszs Updated param names to `subnet_jsonrpc_http` and `subnet_jsonrpc_ws`. I am strongly against making websocket argument required, as first time we needed it in a year was recently when Monir was dealing with the external subnets. Anyway lets leave that decision for some other PR.

2023-10-13 18:16 UTC, dvdplm commented
> I am strongly against making websocket argument required, as first time we needed it in a year was recently when Monir was dealing with the external subnets. Anyway lets leave that decision for some other PR.

Ok, maybe you're right. We'll discuss it elsewhere.  :)

2023-10-16 09:20 UTC, merged